[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dimos_lcm"
version = "0.1.0"
description = "LCM-Foxglove bridge and message utilities for Dimensional Robotics"
authors = [
    {name = "Dimensional Team", email = "build@dimensionalOS.com"},
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "lcm",
    "foxglove-websocket",
    "numpy",
]

[project.urls]
"Homepage" = "https://github.com/dimensionalOS/dimos-lcm"

[tool.setuptools]
packages = [
    "dimos_lcm", 
    "dimos_lcm.geometry_msgs",
    "dimos_lcm.sensor_msgs", 
    "dimos_lcm.std_msgs",
    "dimos_lcm.nav_msgs",
    "dimos_lcm.diagnostic_msgs",
    "dimos_lcm.actionlib_msgs",
    "dimos_lcm.builtin_interfaces",
    "dimos_lcm.foxglove_msgs",
    "dimos_lcm.shape_msgs",
    "dimos_lcm.stereo_msgs",
    "dimos_lcm.tf2_msgs",
    "dimos_lcm.trajectory_msgs",
    "dimos_lcm.vision_msgs",
    "dimos_lcm.visualization_msgs"
]

[tool.setuptools.package-dir]
"dimos_lcm" = "."
"dimos_lcm.geometry_msgs" = "python_lcm_msgs/lcm_msgs/geometry_msgs"
"dimos_lcm.sensor_msgs" = "python_lcm_msgs/lcm_msgs/sensor_msgs"
"dimos_lcm.std_msgs" = "python_lcm_msgs/lcm_msgs/std_msgs"
"dimos_lcm.nav_msgs" = "python_lcm_msgs/lcm_msgs/nav_msgs"
"dimos_lcm.diagnostic_msgs" = "python_lcm_msgs/lcm_msgs/diagnostic_msgs"
"dimos_lcm.actionlib_msgs" = "python_lcm_msgs/lcm_msgs/actionlib_msgs"
"dimos_lcm.builtin_interfaces" = "python_lcm_msgs/lcm_msgs/builtin_interfaces"
"dimos_lcm.foxglove_msgs" = "python_lcm_msgs/lcm_msgs/foxglove_msgs"
"dimos_lcm.shape_msgs" = "python_lcm_msgs/lcm_msgs/shape_msgs"
"dimos_lcm.stereo_msgs" = "python_lcm_msgs/lcm_msgs/stereo_msgs"
"dimos_lcm.tf2_msgs" = "python_lcm_msgs/lcm_msgs/tf2_msgs"
"dimos_lcm.trajectory_msgs" = "python_lcm_msgs/lcm_msgs/trajectory_msgs"
"dimos_lcm.vision_msgs" = "python_lcm_msgs/lcm_msgs/vision_msgs"
"dimos_lcm.visualization_msgs" = "python_lcm_msgs/lcm_msgs/visualization_msgs"

[tool.setuptools.package-data]
"dimos_lcm" = [
    "*.py", 
    "*.sh", 
    "ros_msgs/**/*", 
    "lcm_files/**/*", 
    "python_lcm_msgs/**/*"
]

