/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package visualization_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class InteractiveMarkerUpdate implements lcm.lcm.LCMEncodable
{
    public int markers_length;

    public int poses_length;

    public int erases_length;

    public String server_id;

    public long seq_num;

    public byte type;

    /**
     * LCM Type: visualization_msgs.InteractiveMarker[markers_length]
     */
    public visualization_msgs.InteractiveMarker markers[];

    /**
     * LCM Type: visualization_msgs.InteractiveMarkerPose[poses_length]
     */
    public visualization_msgs.InteractiveMarkerPose poses[];

    /**
     * LCM Type: string[erases_length]
     */
    public String erases[];

 
    public InteractiveMarkerUpdate()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf6eebb4c4a608b4cL;
 
    public static final byte KEEP_ALIVE = (byte) 0;
    public static final byte UPDATE = (byte) 1;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(visualization_msgs.InteractiveMarkerUpdate.class))
            return 0L;
 
        classes.add(visualization_msgs.InteractiveMarkerUpdate.class);
        long hash = LCM_FINGERPRINT_BASE
             + visualization_msgs.InteractiveMarker._hashRecursive(classes)
             + visualization_msgs.InteractiveMarkerPose._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeInt(this.markers_length); 
 
        outs.writeInt(this.poses_length); 
 
        outs.writeInt(this.erases_length); 
 
        __strbuf = new char[this.server_id.length()]; this.server_id.getChars(0, this.server_id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeLong(this.seq_num); 
 
        outs.writeByte(this.type); 
 
        for (int a = 0; a < this.markers_length; a++) {
            this.markers[a]._encodeRecursive(outs); 
        }
 
        for (int a = 0; a < this.poses_length; a++) {
            this.poses[a]._encodeRecursive(outs); 
        }
 
        for (int a = 0; a < this.erases_length; a++) {
            __strbuf = new char[this.erases[a].length()]; this.erases[a].getChars(0, this.erases[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
    }
 
    public InteractiveMarkerUpdate(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public InteractiveMarkerUpdate(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static visualization_msgs.InteractiveMarkerUpdate _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        visualization_msgs.InteractiveMarkerUpdate o = new visualization_msgs.InteractiveMarkerUpdate();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.markers_length = ins.readInt();
 
        this.poses_length = ins.readInt();
 
        this.erases_length = ins.readInt();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.server_id = new String(__strbuf);
 
        this.seq_num = ins.readLong();
 
        this.type = ins.readByte();
 
        this.markers = new visualization_msgs.InteractiveMarker[(int) markers_length];
        for (int a = 0; a < this.markers_length; a++) {
            this.markers[a] = visualization_msgs.InteractiveMarker._decodeRecursiveFactory(ins);
        }
 
        this.poses = new visualization_msgs.InteractiveMarkerPose[(int) poses_length];
        for (int a = 0; a < this.poses_length; a++) {
            this.poses[a] = visualization_msgs.InteractiveMarkerPose._decodeRecursiveFactory(ins);
        }
 
        this.erases = new String[(int) erases_length];
        for (int a = 0; a < this.erases_length; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.erases[a] = new String(__strbuf);
        }
 
    }
 
    public visualization_msgs.InteractiveMarkerUpdate copy()
    {
        visualization_msgs.InteractiveMarkerUpdate outobj = new visualization_msgs.InteractiveMarkerUpdate();
        outobj.markers_length = this.markers_length;
 
        outobj.poses_length = this.poses_length;
 
        outobj.erases_length = this.erases_length;
 
        outobj.server_id = this.server_id;
 
        outobj.seq_num = this.seq_num;
 
        outobj.type = this.type;
 
        outobj.markers = new visualization_msgs.InteractiveMarker[(int) markers_length];
        for (int a = 0; a < this.markers_length; a++) {
            outobj.markers[a] = this.markers[a].copy();
        }
 
        outobj.poses = new visualization_msgs.InteractiveMarkerPose[(int) poses_length];
        for (int a = 0; a < this.poses_length; a++) {
            outobj.poses[a] = this.poses[a].copy();
        }
 
        outobj.erases = new String[(int) erases_length];
        if (this.erases_length > 0)
            System.arraycopy(this.erases, 0, outobj.erases, 0, (int) this.erases_length); 
        return outobj;
    }
 
}

