/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package geometry_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class PolygonStamped implements lcm.lcm.LCMEncodable
{
    public std_msgs.Header header;

    public geometry_msgs.Polygon polygon;

 
    public PolygonStamped()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x413a2f753630b1d7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(geometry_msgs.PolygonStamped.class))
            return 0L;
 
        classes.add(geometry_msgs.PolygonStamped.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Header._hashRecursive(classes)
             + geometry_msgs.Polygon._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        this.polygon._encodeRecursive(outs); 
 
    }
 
    public PolygonStamped(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public PolygonStamped(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static geometry_msgs.PolygonStamped _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        geometry_msgs.PolygonStamped o = new geometry_msgs.PolygonStamped();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
        this.polygon = geometry_msgs.Polygon._decodeRecursiveFactory(ins);
 
    }
 
    public geometry_msgs.PolygonStamped copy()
    {
        geometry_msgs.PolygonStamped outobj = new geometry_msgs.PolygonStamped();
        outobj.header = this.header.copy();
 
        outobj.polygon = this.polygon.copy();
 
        return outobj;
    }
 
}

