/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package geometry_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Polygon implements lcm.lcm.LCMEncodable
{
    public int points_length;

    /**
     * LCM Type: geometry_msgs.Point32[points_length]
     */
    public geometry_msgs.Point32 points[];

 
    public Polygon()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5634733b354407e8L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(geometry_msgs.Polygon.class))
            return 0L;
 
        classes.add(geometry_msgs.Polygon.class);
        long hash = LCM_FINGERPRINT_BASE
             + geometry_msgs.Point32._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.points_length); 
 
        for (int a = 0; a < this.points_length; a++) {
            this.points[a]._encodeRecursive(outs); 
        }
 
    }
 
    public Polygon(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Polygon(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static geometry_msgs.Polygon _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        geometry_msgs.Polygon o = new geometry_msgs.Polygon();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.points_length = ins.readInt();
 
        this.points = new geometry_msgs.Point32[(int) points_length];
        for (int a = 0; a < this.points_length; a++) {
            this.points[a] = geometry_msgs.Point32._decodeRecursiveFactory(ins);
        }
 
    }
 
    public geometry_msgs.Polygon copy()
    {
        geometry_msgs.Polygon outobj = new geometry_msgs.Polygon();
        outobj.points_length = this.points_length;
 
        outobj.points = new geometry_msgs.Point32[(int) points_length];
        for (int a = 0; a < this.points_length; a++) {
            outobj.points[a] = this.points[a].copy();
        }
 
        return outobj;
    }
 
}

