/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package geometry_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Pose implements lcm.lcm.LCMEncodable
{
    public geometry_msgs.Point position;

    public geometry_msgs.Quaternion orientation;

 
    public Pose()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2d70dd60bd541272L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(geometry_msgs.Pose.class))
            return 0L;
 
        classes.add(geometry_msgs.Pose.class);
        long hash = LCM_FINGERPRINT_BASE
             + geometry_msgs.Point._hashRecursive(classes)
             + geometry_msgs.Quaternion._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.position._encodeRecursive(outs); 
 
        this.orientation._encodeRecursive(outs); 
 
    }
 
    public Pose(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Pose(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static geometry_msgs.Pose _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        geometry_msgs.Pose o = new geometry_msgs.Pose();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.position = geometry_msgs.Point._decodeRecursiveFactory(ins);
 
        this.orientation = geometry_msgs.Quaternion._decodeRecursiveFactory(ins);
 
    }
 
    public geometry_msgs.Pose copy()
    {
        geometry_msgs.Pose outobj = new geometry_msgs.Pose();
        outobj.position = this.position.copy();
 
        outobj.orientation = this.orientation.copy();
 
        return outobj;
    }
 
}

