/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package geometry_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class PoseWithCovariance implements lcm.lcm.LCMEncodable
{
    public geometry_msgs.Pose pose;

    /**
     * LCM Type: double[36]
     */
    public double covariance[];

 
    public PoseWithCovariance()
    {
        covariance = new double[36];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x42dbdfaa69371237L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(geometry_msgs.PoseWithCovariance.class))
            return 0L;
 
        classes.add(geometry_msgs.PoseWithCovariance.class);
        long hash = LCM_FINGERPRINT_BASE
             + geometry_msgs.Pose._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.pose._encodeRecursive(outs); 
 
        for (int a = 0; a < 36; a++) {
            outs.writeDouble(this.covariance[a]); 
        }
 
    }
 
    public PoseWithCovariance(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public PoseWithCovariance(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static geometry_msgs.PoseWithCovariance _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        geometry_msgs.PoseWithCovariance o = new geometry_msgs.PoseWithCovariance();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
        this.covariance = new double[(int) 36];
        for (int a = 0; a < 36; a++) {
            this.covariance[a] = ins.readDouble();
        }
 
    }
 
    public geometry_msgs.PoseWithCovariance copy()
    {
        geometry_msgs.PoseWithCovariance outobj = new geometry_msgs.PoseWithCovariance();
        outobj.pose = this.pose.copy();
 
        outobj.covariance = new double[(int) 36];
        System.arraycopy(this.covariance, 0, outobj.covariance, 0, 36); 
        return outobj;
    }
 
}

