/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package geometry_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Twist implements lcm.lcm.LCMEncodable
{
    public geometry_msgs.Vector3 linear;

    public geometry_msgs.Vector3 angular;

 
    public Twist()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3a4144772922add7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(geometry_msgs.Twist.class))
            return 0L;
 
        classes.add(geometry_msgs.Twist.class);
        long hash = LCM_FINGERPRINT_BASE
             + geometry_msgs.Vector3._hashRecursive(classes)
             + geometry_msgs.Vector3._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.linear._encodeRecursive(outs); 
 
        this.angular._encodeRecursive(outs); 
 
    }
 
    public Twist(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Twist(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static geometry_msgs.Twist _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        geometry_msgs.Twist o = new geometry_msgs.Twist();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.linear = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
        this.angular = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
    }
 
    public geometry_msgs.Twist copy()
    {
        geometry_msgs.Twist outobj = new geometry_msgs.Twist();
        outobj.linear = this.linear.copy();
 
        outobj.angular = this.angular.copy();
 
        return outobj;
    }
 
}

