/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package foxglove_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class CircleAnnotation implements lcm.lcm.LCMEncodable
{
    public builtin_interfaces.Time timestamp;

    public foxglove_msgs.Point2 position;

    public double diameter;

    public double thickness;

    public foxglove_msgs.Color fill_color;

    public foxglove_msgs.Color outline_color;

 
    public CircleAnnotation()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5a3219098258887cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(foxglove_msgs.CircleAnnotation.class))
            return 0L;
 
        classes.add(foxglove_msgs.CircleAnnotation.class);
        long hash = LCM_FINGERPRINT_BASE
             + builtin_interfaces.Time._hashRecursive(classes)
             + foxglove_msgs.Point2._hashRecursive(classes)
             + foxglove_msgs.Color._hashRecursive(classes)
             + foxglove_msgs.Color._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.timestamp._encodeRecursive(outs); 
 
        this.position._encodeRecursive(outs); 
 
        outs.writeDouble(this.diameter); 
 
        outs.writeDouble(this.thickness); 
 
        this.fill_color._encodeRecursive(outs); 
 
        this.outline_color._encodeRecursive(outs); 
 
    }
 
    public CircleAnnotation(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public CircleAnnotation(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static foxglove_msgs.CircleAnnotation _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        foxglove_msgs.CircleAnnotation o = new foxglove_msgs.CircleAnnotation();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
        this.position = foxglove_msgs.Point2._decodeRecursiveFactory(ins);
 
        this.diameter = ins.readDouble();
 
        this.thickness = ins.readDouble();
 
        this.fill_color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
        this.outline_color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
    }
 
    public foxglove_msgs.CircleAnnotation copy()
    {
        foxglove_msgs.CircleAnnotation outobj = new foxglove_msgs.CircleAnnotation();
        outobj.timestamp = this.timestamp.copy();
 
        outobj.position = this.position.copy();
 
        outobj.diameter = this.diameter;
 
        outobj.thickness = this.thickness;
 
        outobj.fill_color = this.fill_color.copy();
 
        outobj.outline_color = this.outline_color.copy();
 
        return outobj;
    }
 
}

