/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package foxglove_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class LaserScan implements lcm.lcm.LCMEncodable
{
    public int ranges_length;

    public int intensities_length;

    public builtin_interfaces.Time timestamp;

    public String frame_id;

    public geometry_msgs.Pose pose;

    public double start_angle;

    public double end_angle;

    /**
     * LCM Type: double[ranges_length]
     */
    public double ranges[];

    /**
     * LCM Type: double[intensities_length]
     */
    public double intensities[];

 
    public LaserScan()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x22e7c769ba6a90c2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(foxglove_msgs.LaserScan.class))
            return 0L;
 
        classes.add(foxglove_msgs.LaserScan.class);
        long hash = LCM_FINGERPRINT_BASE
             + builtin_interfaces.Time._hashRecursive(classes)
             + geometry_msgs.Pose._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeInt(this.ranges_length); 
 
        outs.writeInt(this.intensities_length); 
 
        this.timestamp._encodeRecursive(outs); 
 
        __strbuf = new char[this.frame_id.length()]; this.frame_id.getChars(0, this.frame_id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        this.pose._encodeRecursive(outs); 
 
        outs.writeDouble(this.start_angle); 
 
        outs.writeDouble(this.end_angle); 
 
        for (int a = 0; a < this.ranges_length; a++) {
            outs.writeDouble(this.ranges[a]); 
        }
 
        for (int a = 0; a < this.intensities_length; a++) {
            outs.writeDouble(this.intensities[a]); 
        }
 
    }
 
    public LaserScan(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public LaserScan(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static foxglove_msgs.LaserScan _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        foxglove_msgs.LaserScan o = new foxglove_msgs.LaserScan();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.ranges_length = ins.readInt();
 
        this.intensities_length = ins.readInt();
 
        this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.frame_id = new String(__strbuf);
 
        this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
        this.start_angle = ins.readDouble();
 
        this.end_angle = ins.readDouble();
 
        this.ranges = new double[(int) ranges_length];
        for (int a = 0; a < this.ranges_length; a++) {
            this.ranges[a] = ins.readDouble();
        }
 
        this.intensities = new double[(int) intensities_length];
        for (int a = 0; a < this.intensities_length; a++) {
            this.intensities[a] = ins.readDouble();
        }
 
    }
 
    public foxglove_msgs.LaserScan copy()
    {
        foxglove_msgs.LaserScan outobj = new foxglove_msgs.LaserScan();
        outobj.ranges_length = this.ranges_length;
 
        outobj.intensities_length = this.intensities_length;
 
        outobj.timestamp = this.timestamp.copy();
 
        outobj.frame_id = this.frame_id;
 
        outobj.pose = this.pose.copy();
 
        outobj.start_angle = this.start_angle;
 
        outobj.end_angle = this.end_angle;
 
        outobj.ranges = new double[(int) ranges_length];
        if (this.ranges_length > 0)
            System.arraycopy(this.ranges, 0, outobj.ranges, 0, (int) this.ranges_length); 
        outobj.intensities = new double[(int) intensities_length];
        if (this.intensities_length > 0)
            System.arraycopy(this.intensities, 0, outobj.intensities, 0, (int) this.intensities_length); 
        return outobj;
    }
 
}

