/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package foxglove_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class LocationFix implements lcm.lcm.LCMEncodable
{
    public builtin_interfaces.Time timestamp;

    public String frame_id;

    public double latitude;

    public double longitude;

    public double altitude;

    /**
     * LCM Type: double[9]
     */
    public double position_covariance[];

    public byte position_covariance_type;

 
    public LocationFix()
    {
        position_covariance = new double[9];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc7c172f7d2332f54L;
 
    public static final byte UNKNOWN = (byte) 0;
    public static final byte APPROXIMATED = (byte) 1;
    public static final byte DIAGONAL_KNOWN = (byte) 2;
    public static final byte KNOWN = (byte) 3;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(foxglove_msgs.LocationFix.class))
            return 0L;
 
        classes.add(foxglove_msgs.LocationFix.class);
        long hash = LCM_FINGERPRINT_BASE
             + builtin_interfaces.Time._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp._encodeRecursive(outs); 
 
        __strbuf = new char[this.frame_id.length()]; this.frame_id.getChars(0, this.frame_id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeDouble(this.latitude); 
 
        outs.writeDouble(this.longitude); 
 
        outs.writeDouble(this.altitude); 
 
        for (int a = 0; a < 9; a++) {
            outs.writeDouble(this.position_covariance[a]); 
        }
 
        outs.writeByte(this.position_covariance_type); 
 
    }
 
    public LocationFix(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public LocationFix(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static foxglove_msgs.LocationFix _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        foxglove_msgs.LocationFix o = new foxglove_msgs.LocationFix();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.frame_id = new String(__strbuf);
 
        this.latitude = ins.readDouble();
 
        this.longitude = ins.readDouble();
 
        this.altitude = ins.readDouble();
 
        this.position_covariance = new double[(int) 9];
        for (int a = 0; a < 9; a++) {
            this.position_covariance[a] = ins.readDouble();
        }
 
        this.position_covariance_type = ins.readByte();
 
    }
 
    public foxglove_msgs.LocationFix copy()
    {
        foxglove_msgs.LocationFix outobj = new foxglove_msgs.LocationFix();
        outobj.timestamp = this.timestamp.copy();
 
        outobj.frame_id = this.frame_id;
 
        outobj.latitude = this.latitude;
 
        outobj.longitude = this.longitude;
 
        outobj.altitude = this.altitude;
 
        outobj.position_covariance = new double[(int) 9];
        System.arraycopy(this.position_covariance, 0, outobj.position_covariance, 0, 9); 
        outobj.position_covariance_type = this.position_covariance_type;
 
        return outobj;
    }
 
}

