/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package foxglove_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Log implements lcm.lcm.LCMEncodable
{
    public builtin_interfaces.Time timestamp;

    public byte level;

    public String message;

    public String name;

    public String file;

    public int line;

 
    public Log()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x623dae456e90a1c7L;
 
    public static final byte UNKNOWN = (byte) 0;
    public static final byte DEBUG = (byte) 1;
    public static final byte INFO = (byte) 2;
    public static final byte WARNING = (byte) 3;
    public static final byte ERROR = (byte) 4;
    public static final byte FATAL = (byte) 5;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(foxglove_msgs.Log.class))
            return 0L;
 
        classes.add(foxglove_msgs.Log.class);
        long hash = LCM_FINGERPRINT_BASE
             + builtin_interfaces.Time._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp._encodeRecursive(outs); 
 
        outs.writeByte(this.level); 
 
        __strbuf = new char[this.message.length()]; this.message.getChars(0, this.message.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.name.length()]; this.name.getChars(0, this.name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.file.length()]; this.file.getChars(0, this.file.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.line); 
 
    }
 
    public Log(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Log(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static foxglove_msgs.Log _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        foxglove_msgs.Log o = new foxglove_msgs.Log();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
        this.level = ins.readByte();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.message = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.name = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.file = new String(__strbuf);
 
        this.line = ins.readInt();
 
    }
 
    public foxglove_msgs.Log copy()
    {
        foxglove_msgs.Log outobj = new foxglove_msgs.Log();
        outobj.timestamp = this.timestamp.copy();
 
        outobj.level = this.level;
 
        outobj.message = this.message;
 
        outobj.name = this.name;
 
        outobj.file = this.file;
 
        outobj.line = this.line;
 
        return outobj;
    }
 
}

