/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package foxglove_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class PointsAnnotation implements lcm.lcm.LCMEncodable
{
    public int points_length;

    public int outline_colors_length;

    public builtin_interfaces.Time timestamp;

    public byte type;

    /**
     * LCM Type: foxglove_msgs.Point2[points_length]
     */
    public foxglove_msgs.Point2 points[];

    public foxglove_msgs.Color outline_color;

    /**
     * LCM Type: foxglove_msgs.Color[outline_colors_length]
     */
    public foxglove_msgs.Color outline_colors[];

    public foxglove_msgs.Color fill_color;

    public double thickness;

 
    public PointsAnnotation()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x97465363cc7c2a18L;
 
    public static final byte UNKNOWN = (byte) 0;
    public static final byte POINTS = (byte) 1;
    public static final byte LINE_LOOP = (byte) 2;
    public static final byte LINE_STRIP = (byte) 3;
    public static final byte LINE_LIST = (byte) 4;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(foxglove_msgs.PointsAnnotation.class))
            return 0L;
 
        classes.add(foxglove_msgs.PointsAnnotation.class);
        long hash = LCM_FINGERPRINT_BASE
             + builtin_interfaces.Time._hashRecursive(classes)
             + foxglove_msgs.Point2._hashRecursive(classes)
             + foxglove_msgs.Color._hashRecursive(classes)
             + foxglove_msgs.Color._hashRecursive(classes)
             + foxglove_msgs.Color._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.points_length); 
 
        outs.writeInt(this.outline_colors_length); 
 
        this.timestamp._encodeRecursive(outs); 
 
        outs.writeByte(this.type); 
 
        for (int a = 0; a < this.points_length; a++) {
            this.points[a]._encodeRecursive(outs); 
        }
 
        this.outline_color._encodeRecursive(outs); 
 
        for (int a = 0; a < this.outline_colors_length; a++) {
            this.outline_colors[a]._encodeRecursive(outs); 
        }
 
        this.fill_color._encodeRecursive(outs); 
 
        outs.writeDouble(this.thickness); 
 
    }
 
    public PointsAnnotation(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public PointsAnnotation(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static foxglove_msgs.PointsAnnotation _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        foxglove_msgs.PointsAnnotation o = new foxglove_msgs.PointsAnnotation();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.points_length = ins.readInt();
 
        this.outline_colors_length = ins.readInt();
 
        this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
        this.type = ins.readByte();
 
        this.points = new foxglove_msgs.Point2[(int) points_length];
        for (int a = 0; a < this.points_length; a++) {
            this.points[a] = foxglove_msgs.Point2._decodeRecursiveFactory(ins);
        }
 
        this.outline_color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
        this.outline_colors = new foxglove_msgs.Color[(int) outline_colors_length];
        for (int a = 0; a < this.outline_colors_length; a++) {
            this.outline_colors[a] = foxglove_msgs.Color._decodeRecursiveFactory(ins);
        }
 
        this.fill_color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
        this.thickness = ins.readDouble();
 
    }
 
    public foxglove_msgs.PointsAnnotation copy()
    {
        foxglove_msgs.PointsAnnotation outobj = new foxglove_msgs.PointsAnnotation();
        outobj.points_length = this.points_length;
 
        outobj.outline_colors_length = this.outline_colors_length;
 
        outobj.timestamp = this.timestamp.copy();
 
        outobj.type = this.type;
 
        outobj.points = new foxglove_msgs.Point2[(int) points_length];
        for (int a = 0; a < this.points_length; a++) {
            outobj.points[a] = this.points[a].copy();
        }
 
        outobj.outline_color = this.outline_color.copy();
 
        outobj.outline_colors = new foxglove_msgs.Color[(int) outline_colors_length];
        for (int a = 0; a < this.outline_colors_length; a++) {
            outobj.outline_colors[a] = this.outline_colors[a].copy();
        }
 
        outobj.fill_color = this.fill_color.copy();
 
        outobj.thickness = this.thickness;
 
        return outobj;
    }
 
}

