/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package foxglove_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class RawImage implements lcm.lcm.LCMEncodable
{
    public int data_length;

    public builtin_interfaces.Time timestamp;

    public String frame_id;

    public int width;

    public int height;

    public String encoding;

    public int step;

    /**
     * LCM Type: byte[data_length]
     */
    public byte data[];

 
    public RawImage()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8dc0da8aa491bb39L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(foxglove_msgs.RawImage.class))
            return 0L;
 
        classes.add(foxglove_msgs.RawImage.class);
        long hash = LCM_FINGERPRINT_BASE
             + builtin_interfaces.Time._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeInt(this.data_length); 
 
        this.timestamp._encodeRecursive(outs); 
 
        __strbuf = new char[this.frame_id.length()]; this.frame_id.getChars(0, this.frame_id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.width); 
 
        outs.writeInt(this.height); 
 
        __strbuf = new char[this.encoding.length()]; this.encoding.getChars(0, this.encoding.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.step); 
 
        if (this.data_length > 0)
            outs.write(this.data, 0, (int) data_length);
 
    }
 
    public RawImage(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public RawImage(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static foxglove_msgs.RawImage _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        foxglove_msgs.RawImage o = new foxglove_msgs.RawImage();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.data_length = ins.readInt();
 
        this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.frame_id = new String(__strbuf);
 
        this.width = ins.readInt();
 
        this.height = ins.readInt();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.encoding = new String(__strbuf);
 
        this.step = ins.readInt();
 
        this.data = new byte[(int) data_length];
        ins.readFully(this.data, 0, (int) data_length); 
    }
 
    public foxglove_msgs.RawImage copy()
    {
        foxglove_msgs.RawImage outobj = new foxglove_msgs.RawImage();
        outobj.data_length = this.data_length;
 
        outobj.timestamp = this.timestamp.copy();
 
        outobj.frame_id = this.frame_id;
 
        outobj.width = this.width;
 
        outobj.height = this.height;
 
        outobj.encoding = this.encoding;
 
        outobj.step = this.step;
 
        outobj.data = new byte[(int) data_length];
        if (this.data_length > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.data_length); 
        return outobj;
    }
 
}

