/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package foxglove_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class TriangleListPrimitive implements lcm.lcm.LCMEncodable
{
    public int points_length;

    public int colors_length;

    public int indices_length;

    public geometry_msgs.Pose pose;

    /**
     * LCM Type: geometry_msgs.Point[points_length]
     */
    public geometry_msgs.Point points[];

    public foxglove_msgs.Color color;

    /**
     * LCM Type: foxglove_msgs.Color[colors_length]
     */
    public foxglove_msgs.Color colors[];

    /**
     * LCM Type: int32_t[indices_length]
     */
    public int indices[];

 
    public TriangleListPrimitive()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xcf3047947917a6ccL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(foxglove_msgs.TriangleListPrimitive.class))
            return 0L;
 
        classes.add(foxglove_msgs.TriangleListPrimitive.class);
        long hash = LCM_FINGERPRINT_BASE
             + geometry_msgs.Pose._hashRecursive(classes)
             + geometry_msgs.Point._hashRecursive(classes)
             + foxglove_msgs.Color._hashRecursive(classes)
             + foxglove_msgs.Color._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.points_length); 
 
        outs.writeInt(this.colors_length); 
 
        outs.writeInt(this.indices_length); 
 
        this.pose._encodeRecursive(outs); 
 
        for (int a = 0; a < this.points_length; a++) {
            this.points[a]._encodeRecursive(outs); 
        }
 
        this.color._encodeRecursive(outs); 
 
        for (int a = 0; a < this.colors_length; a++) {
            this.colors[a]._encodeRecursive(outs); 
        }
 
        for (int a = 0; a < this.indices_length; a++) {
            outs.writeInt(this.indices[a]); 
        }
 
    }
 
    public TriangleListPrimitive(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public TriangleListPrimitive(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static foxglove_msgs.TriangleListPrimitive _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        foxglove_msgs.TriangleListPrimitive o = new foxglove_msgs.TriangleListPrimitive();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.points_length = ins.readInt();
 
        this.colors_length = ins.readInt();
 
        this.indices_length = ins.readInt();
 
        this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
        this.points = new geometry_msgs.Point[(int) points_length];
        for (int a = 0; a < this.points_length; a++) {
            this.points[a] = geometry_msgs.Point._decodeRecursiveFactory(ins);
        }
 
        this.color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
        this.colors = new foxglove_msgs.Color[(int) colors_length];
        for (int a = 0; a < this.colors_length; a++) {
            this.colors[a] = foxglove_msgs.Color._decodeRecursiveFactory(ins);
        }
 
        this.indices = new int[(int) indices_length];
        for (int a = 0; a < this.indices_length; a++) {
            this.indices[a] = ins.readInt();
        }
 
    }
 
    public foxglove_msgs.TriangleListPrimitive copy()
    {
        foxglove_msgs.TriangleListPrimitive outobj = new foxglove_msgs.TriangleListPrimitive();
        outobj.points_length = this.points_length;
 
        outobj.colors_length = this.colors_length;
 
        outobj.indices_length = this.indices_length;
 
        outobj.pose = this.pose.copy();
 
        outobj.points = new geometry_msgs.Point[(int) points_length];
        for (int a = 0; a < this.points_length; a++) {
            outobj.points[a] = this.points[a].copy();
        }
 
        outobj.color = this.color.copy();
 
        outobj.colors = new foxglove_msgs.Color[(int) colors_length];
        for (int a = 0; a < this.colors_length; a++) {
            outobj.colors[a] = this.colors[a].copy();
        }
 
        outobj.indices = new int[(int) indices_length];
        if (this.indices_length > 0)
            System.arraycopy(this.indices, 0, outobj.indices, 0, (int) this.indices_length); 
        return outobj;
    }
 
}

