/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package std_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Bool implements lcm.lcm.LCMEncodable
{
    public boolean data;

 
    public Bool()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0f5f7835284a871fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(std_msgs.Bool.class))
            return 0L;
 
        classes.add(std_msgs.Bool.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.data ? 1 : 0); 
 
    }
 
    public Bool(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Bool(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static std_msgs.Bool _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        std_msgs.Bool o = new std_msgs.Bool();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.data = ins.readByte()!=0;
 
    }
 
    public std_msgs.Bool copy()
    {
        std_msgs.Bool outobj = new std_msgs.Bool();
        outobj.data = this.data;
 
        return outobj;
    }
 
}

