/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package std_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Int64MultiArray implements lcm.lcm.LCMEncodable
{
    public int data_length;

    public std_msgs.MultiArrayLayout layout;

    /**
     * LCM Type: int64_t[data_length]
     */
    public long data[];

 
    public Int64MultiArray()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xaa51366c8f22187eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(std_msgs.Int64MultiArray.class))
            return 0L;
 
        classes.add(std_msgs.Int64MultiArray.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.MultiArrayLayout._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.data_length); 
 
        this.layout._encodeRecursive(outs); 
 
        for (int a = 0; a < this.data_length; a++) {
            outs.writeLong(this.data[a]); 
        }
 
    }
 
    public Int64MultiArray(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Int64MultiArray(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static std_msgs.Int64MultiArray _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        std_msgs.Int64MultiArray o = new std_msgs.Int64MultiArray();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.data_length = ins.readInt();
 
        this.layout = std_msgs.MultiArrayLayout._decodeRecursiveFactory(ins);
 
        this.data = new long[(int) data_length];
        for (int a = 0; a < this.data_length; a++) {
            this.data[a] = ins.readLong();
        }
 
    }
 
    public std_msgs.Int64MultiArray copy()
    {
        std_msgs.Int64MultiArray outobj = new std_msgs.Int64MultiArray();
        outobj.data_length = this.data_length;
 
        outobj.layout = this.layout.copy();
 
        outobj.data = new long[(int) data_length];
        if (this.data_length > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.data_length); 
        return outobj;
    }
 
}

