/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package std_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Time implements lcm.lcm.LCMEncodable
{
    public int sec;

    public int nsec;

 
    public Time()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xde1d24a3a8ecb648L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(std_msgs.Time.class))
            return 0L;
 
        classes.add(std_msgs.Time.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.sec); 
 
        outs.writeInt(this.nsec); 
 
    }
 
    public Time(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Time(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static std_msgs.Time _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        std_msgs.Time o = new std_msgs.Time();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.sec = ins.readInt();
 
        this.nsec = ins.readInt();
 
    }
 
    public std_msgs.Time copy()
    {
        std_msgs.Time outobj = new std_msgs.Time();
        outobj.sec = this.sec;
 
        outobj.nsec = this.nsec;
 
        return outobj;
    }
 
}

