"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import *
from lcm_msgs import std_msgs
from .ObjectHypothesisWithPose import ObjectHypothesisWithPose
from .BoundingBox2D import BoundingBox2D
class Detection2D(object):

    __slots__ = ["results_length", "header", "results", "bbox", "id"]

    __typenames__ = ["int32_t", "std_msgs.Header", "ObjectHypothesisWithPose", "BoundingBox2D", "string"]

    __dimensions__ = [None, None, ["results_length"], None, None]

    def __init__(self):
        self.results_length = 0
        """ LCM Type: int32_t """
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.results = []
        """ LCM Type: ObjectHypothesisWithPose[results_length] """
        self.bbox = BoundingBox2D()
        """ LCM Type: BoundingBox2D """
        self.id = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(Detection2D._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.results_length))
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        for i0 in range(self.results_length):
            assert self.results[i0]._get_packed_fingerprint() == ObjectHypothesisWithPose._get_packed_fingerprint()
            self.results[i0]._encode_one(buf)
        assert self.bbox._get_packed_fingerprint() == BoundingBox2D._get_packed_fingerprint()
        self.bbox._encode_one(buf)
        __id_encoded = self.id.encode('utf-8')
        buf.write(struct.pack('>I', len(__id_encoded)+1))
        buf.write(__id_encoded)
        buf.write(b"\0")

    @classmethod
    def decode(cls, data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cls._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cls._decode_one(buf)

    @classmethod
    def _decode_one(cls, buf):
        self = Detection2D()
        self.results_length = struct.unpack(">i", buf.read(4))[0]
        self.header = std_msgs.Header._decode_one(buf)
        self.results = []
        for i0 in range(self.results_length):
            self.results.append(ObjectHypothesisWithPose._decode_one(buf))
        self.bbox = BoundingBox2D._decode_one(buf)
        __id_len = struct.unpack('>I', buf.read(4))[0]
        self.id = buf.read(__id_len)[:-1].decode('utf-8', 'replace')
        return self

    @classmethod
    def _get_hash_recursive(cls, parents):
        if cls in parents: return 0
        newparents = parents + [cls]
        tmphash = (0x7c62020c10a78d22+ std_msgs.Header._get_hash_recursive(newparents)+ ObjectHypothesisWithPose._get_hash_recursive(newparents)+ BoundingBox2D._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @classmethod
    def _get_packed_fingerprint(cls):
        if cls._packed_fingerprint is None:
            cls._packed_fingerprint = struct.pack(">Q", cls._get_hash_recursive([]))
        return cls._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cls._get_packed_fingerprint())[0]

