/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package nav_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class OccupancyGrid implements lcm.lcm.LCMEncodable
{
    public int data_length;

    public std_msgs.Header header;

    public nav_msgs.MapMetaData info;

    /**
     * LCM Type: int8_t[data_length]
     */
    public byte data[];

 
    public OccupancyGrid()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9e67f3f149308d87L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(nav_msgs.OccupancyGrid.class))
            return 0L;
 
        classes.add(nav_msgs.OccupancyGrid.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Header._hashRecursive(classes)
             + nav_msgs.MapMetaData._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.data_length); 
 
        this.header._encodeRecursive(outs); 
 
        this.info._encodeRecursive(outs); 
 
        if (this.data_length > 0)
            outs.write(this.data, 0, (int) data_length);
 
    }
 
    public OccupancyGrid(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public OccupancyGrid(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static nav_msgs.OccupancyGrid _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        nav_msgs.OccupancyGrid o = new nav_msgs.OccupancyGrid();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.data_length = ins.readInt();
 
        this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
        this.info = nav_msgs.MapMetaData._decodeRecursiveFactory(ins);
 
        this.data = new byte[(int) data_length];
        ins.readFully(this.data, 0, (int) data_length); 
    }
 
    public nav_msgs.OccupancyGrid copy()
    {
        nav_msgs.OccupancyGrid outobj = new nav_msgs.OccupancyGrid();
        outobj.data_length = this.data_length;
 
        outobj.header = this.header.copy();
 
        outobj.info = this.info.copy();
 
        outobj.data = new byte[(int) data_length];
        if (this.data_length > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.data_length); 
        return outobj;
    }
 
}

