"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class LaserEcho(object):

    __slots__ = ["echoes_length", "echoes"]

    __typenames__ = ["int32_t", "float"]

    __dimensions__ = [None, ["echoes_length"]]

    def __init__(self):
        self.echoes_length = 0
        """ LCM Type: int32_t """
        self.echoes = []
        """ LCM Type: float[echoes_length] """

    def encode(self):
        buf = BytesIO()
        buf.write(LaserEcho._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.echoes_length))
        buf.write(struct.pack('>%df' % self.echoes_length, *self.echoes[:self.echoes_length]))

    @classmethod
    def decode(cls, data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cls._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cls._decode_one(buf)

    @classmethod
    def _decode_one(cls, buf):
        self = LaserEcho()
        self.echoes_length = struct.unpack(">i", buf.read(4))[0]
        self.echoes = struct.unpack('>%df' % self.echoes_length, buf.read(self.echoes_length * 4))
        return self

    @classmethod
    def _get_hash_recursive(cls, parents):
        if cls in parents: return 0
        tmphash = (0xc45702116c7d0a2e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @classmethod
    def _get_packed_fingerprint(cls):
        if cls._packed_fingerprint is None:
            cls._packed_fingerprint = struct.pack(">Q", cls._get_hash_recursive([]))
        return cls._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cls._get_packed_fingerprint())[0]

