"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import geometry_msgs
from lcm_msgs import std_msgs
class MagneticField(object):

    __slots__ = ["header", "magnetic_field", "magnetic_field_covariance"]

    __typenames__ = ["std_msgs.Header", "geometry_msgs.Vector3", "double"]

    __dimensions__ = [None, None, [9]]

    def __init__(self):
        self.header = std_msgs.Header()
        """ LCM Type: std_msgs.Header """
        self.magnetic_field = geometry_msgs.Vector3()
        """ LCM Type: geometry_msgs.Vector3 """
        self.magnetic_field_covariance = [ 0.0 for dim0 in range(9) ]
        """ LCM Type: double[9] """

    def encode(self):
        buf = BytesIO()
        buf.write(MagneticField._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.magnetic_field._get_packed_fingerprint() == geometry_msgs.Vector3._get_packed_fingerprint()
        self.magnetic_field._encode_one(buf)
        buf.write(struct.pack('>9d', *self.magnetic_field_covariance[:9]))

    @classmethod
    def decode(cls, data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cls._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cls._decode_one(buf)

    @classmethod
    def _decode_one(cls, buf):
        self = MagneticField()
        self.header = std_msgs.Header._decode_one(buf)
        self.magnetic_field = geometry_msgs.Vector3._decode_one(buf)
        self.magnetic_field_covariance = struct.unpack('>9d', buf.read(72))
        return self

    @classmethod
    def _get_hash_recursive(cls, parents):
        if cls in parents: return 0
        newparents = parents + [cls]
        tmphash = (0xbfeb021e4751ed88+ std_msgs.Header._get_hash_recursive(newparents)+ geometry_msgs.Vector3._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @classmethod
    def _get_packed_fingerprint(cls):
        if cls._packed_fingerprint is None:
            cls._packed_fingerprint = struct.pack(">Q", cls._get_hash_recursive([]))
        return cls._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cls._get_packed_fingerprint())[0]

