"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from lcm_msgs import std_msgs
class TimeReference(object):

    msg_name = "TimeReference"

    __slots__ = ["header", "time_ref", "source"]

    __typenames__ = ["std_msgs.Header", "std_msgs.Time", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self, header=std_msgs.Header(), time_ref=std_msgs.Time(), source=""):
        # LCM Type: std_msgs.Header
        self.header = header
        # LCM Type: std_msgs.Time
        self.time_ref = time_ref
        # LCM Type: string
        self.source = source

    def encode(self):
        buf = BytesIO()
        buf.write(TimeReference._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.time_ref._get_packed_fingerprint() == std_msgs.Time._get_packed_fingerprint()
        self.time_ref._encode_one(buf)
        __source_encoded = self.source.encode('utf-8')
        buf.write(struct.pack('>I', len(__source_encoded)+1))
        buf.write(__source_encoded)
        buf.write(b"\0")

    @classmethod
    def decode(cls, data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cls._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cls._decode_one(buf)

    @classmethod
    def _decode_one(cls, buf):
        self = TimeReference()
        self.header = std_msgs.Header._decode_one(buf)
        self.time_ref = std_msgs.Time._decode_one(buf)
        __source_len = struct.unpack('>I', buf.read(4))[0]
        self.source = buf.read(__source_len)[:-1].decode('utf-8', 'replace')
        return self

    @classmethod
    def _get_hash_recursive(cls, parents):
        if cls in parents: return 0
        newparents = parents + [cls]
        tmphash = (0x1a6b1c8c5abae6db+ std_msgs.Header._get_hash_recursive(newparents)+ std_msgs.Time._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @classmethod
    def _get_packed_fingerprint(cls):
        if cls._packed_fingerprint is None:
            cls._packed_fingerprint = struct.pack(">Q", cls._get_hash_recursive([]))
        return cls._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cls._get_packed_fingerprint())[0]

