"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import lcm_msgs.geometry_msgs as geometry_msgs

import lcm_msgs.std_msgs as std_msgs

class AccelWithCovarianceStamped(object):

    msg_name = "geometry_msgs.AccelWithCovarianceStamped"

    __slots__ = ["header", "accel"]

    __typenames__ = ["std_msgs.Header", "geometry_msgs.AccelWithCovariance"]

    __dimensions__ = [None, None]

    def __init__(self, header=std_msgs.Header(), accel=geometry_msgs.AccelWithCovariance()):
        # LCM Type: std_msgs.Header
        self.header = header
        # LCM Type: geometry_msgs.AccelWithCovariance
        self.accel = accel

    def encode(self):
        buf = BytesIO()
        buf.write(AccelWithCovarianceStamped._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == std_msgs.Header._get_packed_fingerprint()
        self.header._encode_one(buf)
        assert self.accel._get_packed_fingerprint() == geometry_msgs.AccelWithCovariance._get_packed_fingerprint()
        self.accel._encode_one(buf)

    @classmethod
    def decode(cls, data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cls._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cls._decode_one(buf)

    @classmethod
    def _decode_one(cls, buf):
        self = AccelWithCovarianceStamped()
        self.header = std_msgs.Header._decode_one(buf)
        self.accel = geometry_msgs.AccelWithCovariance._decode_one(buf)
        return self

    @classmethod
    def _get_hash_recursive(cls, parents):
        if cls in parents: return 0
        newparents = parents + [cls]
        tmphash = (0xf012322e268930c2+ std_msgs.Header._get_hash_recursive(newparents)+ geometry_msgs.AccelWithCovariance._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @classmethod
    def _get_packed_fingerprint(cls):
        if cls._packed_fingerprint is None:
            cls._packed_fingerprint = struct.pack(">Q", cls._get_hash_recursive([]))
        return cls._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cls._get_packed_fingerprint())[0]

