"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import lcm_msgs.geometry_msgs as geometry_msgs

class Wrench(object):

    msg_name = "geometry_msgs.Wrench"

    __slots__ = ["force", "torque"]

    __typenames__ = ["geometry_msgs.Vector3", "geometry_msgs.Vector3"]

    __dimensions__ = [None, None]

    def __init__(self, force=geometry_msgs.Vector3(), torque=geometry_msgs.Vector3()):
        # LCM Type: geometry_msgs.Vector3
        self.force = force
        # LCM Type: geometry_msgs.Vector3
        self.torque = torque

    def encode(self):
        buf = BytesIO()
        buf.write(Wrench._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.force._get_packed_fingerprint() == geometry_msgs.Vector3._get_packed_fingerprint()
        self.force._encode_one(buf)
        assert self.torque._get_packed_fingerprint() == geometry_msgs.Vector3._get_packed_fingerprint()
        self.torque._encode_one(buf)

    @classmethod
    def decode(cls, data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cls._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cls._decode_one(buf)

    @classmethod
    def _decode_one(cls, buf):
        self = Wrench()
        self.force = geometry_msgs.Vector3._decode_one(buf)
        self.torque = geometry_msgs.Vector3._decode_one(buf)
        return self

    @classmethod
    def _get_hash_recursive(cls, parents):
        if cls in parents: return 0
        newparents = parents + [cls]
        tmphash = (0x980c3aea984c9a6+ geometry_msgs.Vector3._get_hash_recursive(newparents)+ geometry_msgs.Vector3._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @classmethod
    def _get_packed_fingerprint(cls):
        if cls._packed_fingerprint is None:
            cls._packed_fingerprint = struct.pack(">Q", cls._get_hash_recursive([]))
        return cls._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cls._get_packed_fingerprint())[0]

