/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package actionlib_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class GoalID implements lcm.lcm.LCMEncodable
{
    public std_msgs.Time stamp;

    public String id;

 
    public GoalID()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xef36683ef0767e95L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(actionlib_msgs.GoalID.class))
            return 0L;
 
        classes.add(actionlib_msgs.GoalID.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Time._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        this.stamp._encodeRecursive(outs); 
 
        __strbuf = new char[this.id.length()]; this.id.getChars(0, this.id.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public GoalID(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public GoalID(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static actionlib_msgs.GoalID _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        actionlib_msgs.GoalID o = new actionlib_msgs.GoalID();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.stamp = std_msgs.Time._decodeRecursiveFactory(ins);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.id = new String(__strbuf);
 
    }
 
    public actionlib_msgs.GoalID copy()
    {
        actionlib_msgs.GoalID outobj = new actionlib_msgs.GoalID();
        outobj.stamp = this.stamp.copy();
 
        outobj.id = this.id;
 
        return outobj;
    }
 
}

