/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package actionlib_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class GoalStatusArray implements lcm.lcm.LCMEncodable
{
    public int status_list_length;

    public std_msgs.Header header;

    /**
     * LCM Type: actionlib_msgs.GoalStatus[status_list_length]
     */
    public actionlib_msgs.GoalStatus status_list[];

 
    public GoalStatusArray()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0f5c35b2e7eed0faL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(actionlib_msgs.GoalStatusArray.class))
            return 0L;
 
        classes.add(actionlib_msgs.GoalStatusArray.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Header._hashRecursive(classes)
             + actionlib_msgs.GoalStatus._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.status_list_length); 
 
        this.header._encodeRecursive(outs); 
 
        for (int a = 0; a < this.status_list_length; a++) {
            this.status_list[a]._encodeRecursive(outs); 
        }
 
    }
 
    public GoalStatusArray(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public GoalStatusArray(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static actionlib_msgs.GoalStatusArray _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        actionlib_msgs.GoalStatusArray o = new actionlib_msgs.GoalStatusArray();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.status_list_length = ins.readInt();
 
        this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
        this.status_list = new actionlib_msgs.GoalStatus[(int) status_list_length];
        for (int a = 0; a < this.status_list_length; a++) {
            this.status_list[a] = actionlib_msgs.GoalStatus._decodeRecursiveFactory(ins);
        }
 
    }
 
    public actionlib_msgs.GoalStatusArray copy()
    {
        actionlib_msgs.GoalStatusArray outobj = new actionlib_msgs.GoalStatusArray();
        outobj.status_list_length = this.status_list_length;
 
        outobj.header = this.header.copy();
 
        outobj.status_list = new actionlib_msgs.GoalStatus[(int) status_list_length];
        for (int a = 0; a < this.status_list_length; a++) {
            outobj.status_list[a] = this.status_list[a].copy();
        }
 
        return outobj;
    }
 
}

