[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lcm_msgs"
version = "0.1.2"
description = "LCM generated Python bindings for ROS based types"
authors = [
    {name = "Dimensional"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "lcm",
]

[project.urls]
"Homepage" = "https://github.com/dimensional/lcm_msgs"
