/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package sensor_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Image implements lcm.lcm.LCMEncodable
{
    public int data_length;

    public std_msgs.Header header;

    public int height;

    public int width;

    public String encoding;

    public byte is_bigendian;

    public int step;

    /**
     * LCM Type: byte[data_length]
     */
    public byte data[];

 
    public Image()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x79d36c21d3c16094L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(sensor_msgs.Image.class))
            return 0L;
 
        classes.add(sensor_msgs.Image.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeInt(this.data_length); 
 
        this.header._encodeRecursive(outs); 
 
        outs.writeInt(this.height); 
 
        outs.writeInt(this.width); 
 
        __strbuf = new char[this.encoding.length()]; this.encoding.getChars(0, this.encoding.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeByte(this.is_bigendian); 
 
        outs.writeInt(this.step); 
 
        if (this.data_length > 0)
            outs.write(this.data, 0, (int) data_length);
 
    }
 
    public Image(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Image(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static sensor_msgs.Image _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        sensor_msgs.Image o = new sensor_msgs.Image();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.data_length = ins.readInt();
 
        this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
        this.height = ins.readInt();
 
        this.width = ins.readInt();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.encoding = new String(__strbuf);
 
        this.is_bigendian = ins.readByte();
 
        this.step = ins.readInt();
 
        this.data = new byte[(int) data_length];
        ins.readFully(this.data, 0, (int) data_length); 
    }
 
    public sensor_msgs.Image copy()
    {
        sensor_msgs.Image outobj = new sensor_msgs.Image();
        outobj.data_length = this.data_length;
 
        outobj.header = this.header.copy();
 
        outobj.height = this.height;
 
        outobj.width = this.width;
 
        outobj.encoding = this.encoding;
 
        outobj.is_bigendian = this.is_bigendian;
 
        outobj.step = this.step;
 
        outobj.data = new byte[(int) data_length];
        if (this.data_length > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.data_length); 
        return outobj;
    }
 
}

