/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package sensor_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class MultiEchoLaserScan implements lcm.lcm.LCMEncodable
{
    public int ranges_length;

    public int intensities_length;

    public std_msgs.Header header;

    public float angle_min;

    public float angle_max;

    public float angle_increment;

    public float time_increment;

    public float scan_time;

    public float range_min;

    public float range_max;

    /**
     * LCM Type: sensor_msgs.LaserEcho[ranges_length]
     */
    public sensor_msgs.LaserEcho ranges[];

    /**
     * LCM Type: sensor_msgs.LaserEcho[intensities_length]
     */
    public sensor_msgs.LaserEcho intensities[];

 
    public MultiEchoLaserScan()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf02a6253849d18e2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(sensor_msgs.MultiEchoLaserScan.class))
            return 0L;
 
        classes.add(sensor_msgs.MultiEchoLaserScan.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Header._hashRecursive(classes)
             + sensor_msgs.LaserEcho._hashRecursive(classes)
             + sensor_msgs.LaserEcho._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.ranges_length); 
 
        outs.writeInt(this.intensities_length); 
 
        this.header._encodeRecursive(outs); 
 
        outs.writeFloat(this.angle_min); 
 
        outs.writeFloat(this.angle_max); 
 
        outs.writeFloat(this.angle_increment); 
 
        outs.writeFloat(this.time_increment); 
 
        outs.writeFloat(this.scan_time); 
 
        outs.writeFloat(this.range_min); 
 
        outs.writeFloat(this.range_max); 
 
        for (int a = 0; a < this.ranges_length; a++) {
            this.ranges[a]._encodeRecursive(outs); 
        }
 
        for (int a = 0; a < this.intensities_length; a++) {
            this.intensities[a]._encodeRecursive(outs); 
        }
 
    }
 
    public MultiEchoLaserScan(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public MultiEchoLaserScan(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static sensor_msgs.MultiEchoLaserScan _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        sensor_msgs.MultiEchoLaserScan o = new sensor_msgs.MultiEchoLaserScan();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.ranges_length = ins.readInt();
 
        this.intensities_length = ins.readInt();
 
        this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
        this.angle_min = ins.readFloat();
 
        this.angle_max = ins.readFloat();
 
        this.angle_increment = ins.readFloat();
 
        this.time_increment = ins.readFloat();
 
        this.scan_time = ins.readFloat();
 
        this.range_min = ins.readFloat();
 
        this.range_max = ins.readFloat();
 
        this.ranges = new sensor_msgs.LaserEcho[(int) ranges_length];
        for (int a = 0; a < this.ranges_length; a++) {
            this.ranges[a] = sensor_msgs.LaserEcho._decodeRecursiveFactory(ins);
        }
 
        this.intensities = new sensor_msgs.LaserEcho[(int) intensities_length];
        for (int a = 0; a < this.intensities_length; a++) {
            this.intensities[a] = sensor_msgs.LaserEcho._decodeRecursiveFactory(ins);
        }
 
    }
 
    public sensor_msgs.MultiEchoLaserScan copy()
    {
        sensor_msgs.MultiEchoLaserScan outobj = new sensor_msgs.MultiEchoLaserScan();
        outobj.ranges_length = this.ranges_length;
 
        outobj.intensities_length = this.intensities_length;
 
        outobj.header = this.header.copy();
 
        outobj.angle_min = this.angle_min;
 
        outobj.angle_max = this.angle_max;
 
        outobj.angle_increment = this.angle_increment;
 
        outobj.time_increment = this.time_increment;
 
        outobj.scan_time = this.scan_time;
 
        outobj.range_min = this.range_min;
 
        outobj.range_max = this.range_max;
 
        outobj.ranges = new sensor_msgs.LaserEcho[(int) ranges_length];
        for (int a = 0; a < this.ranges_length; a++) {
            outobj.ranges[a] = this.ranges[a].copy();
        }
 
        outobj.intensities = new sensor_msgs.LaserEcho[(int) intensities_length];
        for (int a = 0; a < this.intensities_length; a++) {
            outobj.intensities[a] = this.intensities[a].copy();
        }
 
        return outobj;
    }
 
}

