/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package sensor_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class PointCloud2 implements lcm.lcm.LCMEncodable
{
    public int fields_length;

    public int data_length;

    public std_msgs.Header header;

    public int height;

    public int width;

    /**
     * LCM Type: sensor_msgs.PointField[fields_length]
     */
    public sensor_msgs.PointField fields[];

    public boolean is_bigendian;

    public int point_step;

    public int row_step;

    /**
     * LCM Type: byte[data_length]
     */
    public byte data[];

    public boolean is_dense;

 
    public PointCloud2()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xeabe7183c4d74215L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(sensor_msgs.PointCloud2.class))
            return 0L;
 
        classes.add(sensor_msgs.PointCloud2.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Header._hashRecursive(classes)
             + sensor_msgs.PointField._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.fields_length); 
 
        outs.writeInt(this.data_length); 
 
        this.header._encodeRecursive(outs); 
 
        outs.writeInt(this.height); 
 
        outs.writeInt(this.width); 
 
        for (int a = 0; a < this.fields_length; a++) {
            this.fields[a]._encodeRecursive(outs); 
        }
 
        outs.writeByte( this.is_bigendian ? 1 : 0); 
 
        outs.writeInt(this.point_step); 
 
        outs.writeInt(this.row_step); 
 
        if (this.data_length > 0)
            outs.write(this.data, 0, (int) data_length);
 
        outs.writeByte( this.is_dense ? 1 : 0); 
 
    }
 
    public PointCloud2(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public PointCloud2(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static sensor_msgs.PointCloud2 _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        sensor_msgs.PointCloud2 o = new sensor_msgs.PointCloud2();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.fields_length = ins.readInt();
 
        this.data_length = ins.readInt();
 
        this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
        this.height = ins.readInt();
 
        this.width = ins.readInt();
 
        this.fields = new sensor_msgs.PointField[(int) fields_length];
        for (int a = 0; a < this.fields_length; a++) {
            this.fields[a] = sensor_msgs.PointField._decodeRecursiveFactory(ins);
        }
 
        this.is_bigendian = ins.readByte()!=0;
 
        this.point_step = ins.readInt();
 
        this.row_step = ins.readInt();
 
        this.data = new byte[(int) data_length];
        ins.readFully(this.data, 0, (int) data_length); 
        this.is_dense = ins.readByte()!=0;
 
    }
 
    public sensor_msgs.PointCloud2 copy()
    {
        sensor_msgs.PointCloud2 outobj = new sensor_msgs.PointCloud2();
        outobj.fields_length = this.fields_length;
 
        outobj.data_length = this.data_length;
 
        outobj.header = this.header.copy();
 
        outobj.height = this.height;
 
        outobj.width = this.width;
 
        outobj.fields = new sensor_msgs.PointField[(int) fields_length];
        for (int a = 0; a < this.fields_length; a++) {
            outobj.fields[a] = this.fields[a].copy();
        }
 
        outobj.is_bigendian = this.is_bigendian;
 
        outobj.point_step = this.point_step;
 
        outobj.row_step = this.row_step;
 
        outobj.data = new byte[(int) data_length];
        if (this.data_length > 0)
            System.arraycopy(this.data, 0, outobj.data, 0, (int) this.data_length); 
        outobj.is_dense = this.is_dense;
 
        return outobj;
    }
 
}

