/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package sensor_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class PointCloud implements lcm.lcm.LCMEncodable
{
    public int points_length;

    public int channels_length;

    public std_msgs.Header header;

    /**
     * LCM Type: geometry_msgs.Point32[points_length]
     */
    public geometry_msgs.Point32 points[];

    /**
     * LCM Type: sensor_msgs.ChannelFloat32[channels_length]
     */
    public sensor_msgs.ChannelFloat32 channels[];

 
    public PointCloud()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3ff7dc99e345164eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(sensor_msgs.PointCloud.class))
            return 0L;
 
        classes.add(sensor_msgs.PointCloud.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Header._hashRecursive(classes)
             + geometry_msgs.Point32._hashRecursive(classes)
             + sensor_msgs.ChannelFloat32._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.points_length); 
 
        outs.writeInt(this.channels_length); 
 
        this.header._encodeRecursive(outs); 
 
        for (int a = 0; a < this.points_length; a++) {
            this.points[a]._encodeRecursive(outs); 
        }
 
        for (int a = 0; a < this.channels_length; a++) {
            this.channels[a]._encodeRecursive(outs); 
        }
 
    }
 
    public PointCloud(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public PointCloud(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static sensor_msgs.PointCloud _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        sensor_msgs.PointCloud o = new sensor_msgs.PointCloud();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.points_length = ins.readInt();
 
        this.channels_length = ins.readInt();
 
        this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
        this.points = new geometry_msgs.Point32[(int) points_length];
        for (int a = 0; a < this.points_length; a++) {
            this.points[a] = geometry_msgs.Point32._decodeRecursiveFactory(ins);
        }
 
        this.channels = new sensor_msgs.ChannelFloat32[(int) channels_length];
        for (int a = 0; a < this.channels_length; a++) {
            this.channels[a] = sensor_msgs.ChannelFloat32._decodeRecursiveFactory(ins);
        }
 
    }
 
    public sensor_msgs.PointCloud copy()
    {
        sensor_msgs.PointCloud outobj = new sensor_msgs.PointCloud();
        outobj.points_length = this.points_length;
 
        outobj.channels_length = this.channels_length;
 
        outobj.header = this.header.copy();
 
        outobj.points = new geometry_msgs.Point32[(int) points_length];
        for (int a = 0; a < this.points_length; a++) {
            outobj.points[a] = this.points[a].copy();
        }
 
        outobj.channels = new sensor_msgs.ChannelFloat32[(int) channels_length];
        for (int a = 0; a < this.channels_length; a++) {
            outobj.channels[a] = this.channels[a].copy();
        }
 
        return outobj;
    }
 
}

