/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package sensor_msgs;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class RelativeHumidity implements lcm.lcm.LCMEncodable
{
    public std_msgs.Header header;

    public double relative_humidity;

    public double variance;

 
    public RelativeHumidity()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1db00395f858f771L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(sensor_msgs.RelativeHumidity.class))
            return 0L;
 
        classes.add(sensor_msgs.RelativeHumidity.class);
        long hash = LCM_FINGERPRINT_BASE
             + std_msgs.Header._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeDouble(this.relative_humidity); 
 
        outs.writeDouble(this.variance); 
 
    }
 
    public RelativeHumidity(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public RelativeHumidity(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static sensor_msgs.RelativeHumidity _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        sensor_msgs.RelativeHumidity o = new sensor_msgs.RelativeHumidity();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
        this.relative_humidity = ins.readDouble();
 
        this.variance = ins.readDouble();
 
    }
 
    public sensor_msgs.RelativeHumidity copy()
    {
        sensor_msgs.RelativeHumidity outobj = new sensor_msgs.RelativeHumidity();
        outobj.header = this.header.copy();
 
        outobj.relative_humidity = this.relative_humidity;
 
        outobj.variance = this.variance;
 
        return outobj;
    }
 
}

